component: http
name: http-nextjs-srC0QJUAy
inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
      - node_modules
  faas:
    runtime: Nodejs12.22
    framework: nextjs
    name: '${name}'
    eip: false
    timeout: 3
    memorySize: 1024
    layers:
      - name: my-blog-layer #  layer名称
        version: 1 
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-beijing
  isAutoCiDeploy: false
org: '1303927255'
app: my-blog
stage: dev
